chessbots/board/blueprints/bots.py
from flask import (Blueprint, request, render_template, jsonify)
from flask import Flask

from chessbots.lib.bot import Bot, BotManager
from chessbots.lib.bot.mockbot import MockBots
from dependency_injector.wiring import inject, Provide
from chessbots.board.containers import Container

bp = Blueprint('bots', __name__, url_prefix='/bots')
app = Flask(__name__)


@bp.route('/', methods=['GET'])
@inject
def get_index(bots: BotManager = Provide[Container.bot_manager]):
    """
    use query parameter for simple filtering
    e.g.:
    /bots/?state=online
    /bots/?state=online&piece=wk
    /bots/?id=herzbube
    """
    return jsonify([bot.data for bot in bots.get_filtered(request.args)]), 200


@bp.route('/', methods=['PATCH'])
@inject
def post_update(bots: BotManager = Provide[Container.bot_manager]):
    """
    use query parameter for simple filtering
    e.g.:
    /bots/?state=online
    /bots/?state=online&piece=wk
    /bots/?id=herzbube
    """
    return jsonify([bot.data for bot in bots.update(request.args)]), 200


@bp.route('/register', methods=['POST'])
@inject
def post_register(bots: BotManager = Provide[Container.bot_manager]):
    """
    json payload:
    ["http://0.0.0.0:8037","http://0.0.0.0:8031/tools/mockbot"]
    """
    return jsonify([bot.data for bot in bots.add(request.json)]), 200


@bp.route('/dashboard', methods=['GET'])
@inject
def get_dashboard(mockbots: MockBots = Provide[Container.mockbots]):
    return render_template('dashboard.html.j2', mockbots=[bot.url() for bot in mockbots.bots])

chessbots/board/blueprints/mockbot.py
from flask import (Blueprint, jsonify, send_from_directory, send_file)
from chessbots.lib.bot.mockbot import *
from io import BytesIO
from flask import Flask

from chessbots.lib.bot.mockbot import MockBots
from dependency_injector.wiring import inject, Provide
from chessbots.board.containers import Container


bp = Blueprint('mockbot', __name__, url_prefix='/mockbot')
app = Flask(__name__)


@bp.route('/<string:name>', methods=['GET'])
@inject
def get_show(name: str, mockbots: MockBots = Provide[Container.mockbots]):
    if not mockbots.has(name):
        return jsonify({
            'url': url_for('mockbot.get_show', name=name, _external=True),
            'state': 'offline',
        })
    bot = mockbots.get(name)
    return jsonify(bot.data())


@bp.route('/<string:name>/position.jpeg', methods=['GET'])
@inject
def get_picture(
        name: str,
        mockbots: MockBots = Provide[Container.mockbots],
        picture_creator: MockbotPictureCreator = Provide[Container.mockbot_picture_creator]
):
    if not mockbots.has(name):
        return jsonify('not found'), 404
    bot = mockbots.get(name)
    img = picture_creator.create_for_bot(bot)
    img_io = BytesIO()
    img.convert('RGB').save(img_io, 'JPEG')
    img_io.seek(0)
    return send_file(img_io, mimetype='image/jpeg')

chessbots/board/blueprints/tools.py
from flask import (render_template)
import random

import cv2
import numpy as np
from flask import Blueprint
from chessbots.tool.pattern_creator import Pattern8x8With4DataFields
from chessbots.lib.pattern import *
from chessbots.tool.printer import *
from chessbots.lib.captcha import Captcha
from chessbots.lib.captcha.grid import create_angel_points
from chessbots.lib.captcha.position import *
from dependency_injector.wiring import inject, Provide
from chessbots.board.containers import Container
from chessbots.lib.bot.mockbot import *
from chessbots.lib.filesystem import *

bp = Blueprint('script', __name__)


@bp.cli.command('pattern_test')
@inject
def pattern_test(pattern_creator: Pattern8x8With4DataFields = Provide[Container.pattern_creator]):

    board = pattern_creator.create(800)
    text_file = open("build/board_pattern.txt", "w")
    text_file.write(Pattern(txt_to_matrix(board.txt())).txt())
    text_file.close()


@bp.cli.command('board_print')
@inject
def board_print(
        printer: TiledPatternPrinter = Provide[Container.tiled_pattern_printer],
        pattern_creator: Pattern8x8With4DataFields = Provide[Container.pattern_creator]
):
    board = pattern_creator.create(800)
    printer.save_to_files(board, 10, 'build/print/board_print_')


@bp.cli.command('mockbot_pictures')
@inject
def mockbot_pictures(
        mock_picture_creator: MockbotPictureCreator = Provide[Container.mockbot_picture_creator],
):
    mock_picture_creator.create()


@bp.cli.command('test_get_angle_points')
@inject
def test_get_angle_points(

):
    angle_data = [
        # ['', [Point(0, 0), Point(1, 0), Point(1, 0)]],
        # ['', [Point(1, 0), Point(0, 0), Point(1, 0)]],
        # ['', [Point(1, 0), Point(1, 0), Point(0, 0)]],

        # ['', [Point(0, 0), Point(0, 1), Point(0, 1)]],
        # ['', [Point(0, 1), Point(0, 0), Point(0, 1)]],
        # ['', [Point(0, 1), Point(0, 1), Point(0, 0)]],

        ['010010', [Point(0, 0), Point(0, 1), Point(1, 0)]],
        ['010010', [Point(0, 0), Point(1, 0), Point(0, 1)]],

        ['101101', [Point(1, 1), Point(0, 1), Point(1, 0)]],
        ['101101', [Point(1, 1), Point(1, 0), Point(0, 1)]],

        ['000111', [Point(0, 1), Point(0, 0), Point(1, 1)]],
        ['000111', [Point(0, 1), Point(1, 1), Point(0, 0)]],

        ['111000', [Point(1, 0), Point(1, 1), Point(0, 0)]],
        ['111000', [Point(1, 0), Point(0, 0), Point(1, 1)]],

        # ['', [Point(450, 450), Point(450, 510), Point(510, 450)]],
        # ['', [Point(449, 450), Point(509, 449), Point(450, 510)]],

        # ['', [Point(0, 0), Point(0, 1), Point(1, 1)]],
        # ['', [Point(0, 0), Point(1, 1), Point(1, 0)]],
        # ['', [Point(0, 0), Point(-1, 0), Point(0, -1)]],
        # ['', [Point(0, 0), Point(0, -1), Point(-1, 0)]],
    ]
    # for ex, c, a, b in angle_data:
        # ac = get_angle(b, c, a)
        # print('test get_angle', int(ac) == ex, ac, ex, c.txt, a.txt, b.txt)


    data = [
        ['000110', [Point(437, 478), Point(480, 437), Point(521, 481), Point(478, 522), Point(396, 435), Point(439, 394), Point(525, 397), Point(392, 519), Point(565, 440), Point(434, 563)]],
    ]


    for ex, d in angle_data:
        try:
            a, b, c = create_angel_points(d)

            rs = ''.join([''.join([str(m.x) + str(m.y) for m in [a, b, c]])])

            print(ex, rs, rs == ex, a.txt, b.txt, c.txt, get_angle(c, b, a))
        except RuntimeError:
            print('error')

    for ex, d in data:
        a, b, c = create_angel_points(d)
        rs = ''.join([''.join([str(m.x) + str(m.y) for m in [a, b, c]])])

        print(ex, rs, rs == ex, a.txt, b.txt, c.txt, get_angle(c, b, a))

        print(a.txt, b.txt, c.txt, get_angle(c, b, a))


@bp.cli.command('test_captcha')
@inject
def test_captcha(
        mockbots: MockBots = Provide[Container.mockbots],
        mockbot_tester: MockBotTester = Provide[Container.mockbot_tester],
):

    result = [mockbot_tester.test_captcha(bot) for bot in mockbots.bots]
    dump_txt('build/mockbot/_test_result.html', render_template('mockbots.html.j2', result=result))

chessbots/board/templates/dashboard.html
{% extends 'index.html' %}

{% block title %}{{ super() }} - dashboard{% endblock %}

{% block main %}
<main id="dashboard">
    <h1>Dashoard</h1>
    <nav>
        <a href="#bots">Bots</a>
        <a href="#register">Register</a>
        <a href="#botrc">BotRC</a>
    </nav>
    <section id="bots" data-show="1">
        <h2>Filter Bots</h2>
        <form action="#" id="bot-filter">
            <label for="filter">Filter</label>
            <input name="filter" id="filter"/>
            <span id="bot-filter-presets">
                <span data-filter="">all</span>
                <span data-filter="state=online">state=online</span>
                <span data-filter="state=offline">state=offline</span>
            </span>
            <button type="submit" data-method="get" data-action="{{ url_for('bots.get_index') }}">filter</button>
            <button type="submit" data-method="patch" data-action="{{ url_for('bots.post_update') }}">update</button>
        </form>
    </section>
    <section id="register" data-show="0">
        <h2>Register Bots</h2>
        <form action="{{ url_for('bots.post_register') }}" method="post" id="register_form">
            <textarea name="data">
[
    "{{ url_for('mockbot.get_show', name='null', _external=True) }}",
    "{{ mockbots|join("\",\n    \"") }}"
]
            </textarea>
            <button type="submit">Submit</button>
        </form>
    </section>

    <section id="botrc" data-show="0">
        <h2>Remote control bot</h2>
        <form action="#" method="post" id="register_form">
            <input name="bot_address" id="bot_address"/>
            <textarea name="sequence">
[
  [1,-1,3]
]
            </textarea>
            <button type="submit">Submit</button>
        </form>
    </section>
</main>
{% endblock %}

chessbots/board/templates/dashboard.html.j2
{% extends 'index.html.j2' %}

{% block title %}{{ super() }} - dashboard{% endblock %}

{% block main %}
<main id="dashboard">
    <h1>Dashoard</h1>
    <nav>
        <a href="#bots">Bots</a>
        <a href="#register">Register</a>
        <a href="#botrc">BotRC</a>
    </nav>
    <section id="bots" data-show="1">
        <h2>Filter Bots</h2>
        <form action="#" id="bot-filter">
            <label for="filter">Filter</label>
            <input name="filter" id="filter"/>
            <span id="bot-filter-presets">
                <span data-filter="">all</span>
                <span data-filter="state=online">state=online</span>
                <span data-filter="state=offline">state=offline</span>
            </span>
            <button type="submit" data-method="get" data-action="{{ url_for('bots.get_index') }}">filter</button>
            <button type="submit" data-method="patch" data-action="{{ url_for('bots.post_update') }}">update</button>
        </form>
    </section>
    <section id="register" data-show="0">
        <h2>Register Bots</h2>
        <form action="{{ url_for('bots.post_register') }}" method="post" id="register_form">
            <textarea name="data">
[
    "{{ url_for('mockbot.get_show', name='null', _external=True) }}",
    "{{ mockbots|join("\",\n    \"") }}"
]
            </textarea>
            <button type="submit">Submit</button>
        </form>
    </section>

    <section id="botrc" data-show="0">
        <h2>Remote control bot</h2>
        <form action="#" method="post" id="register_form">
            <input name="bot_address" id="bot_address"/>
            <textarea name="sequence">
[
  [1,-1,3]
]
            </textarea>
            <button type="submit">Submit</button>
        </form>
    </section>
</main>
{% endblock %}

chessbots/board/templates/index.html
{% extends 'base.html' %}

{% block title %}chessbots{% endblock %}

{% block body %}
    {% block nav %}
    <nav>
        <ul>
            <li><a href="{{ url_for('index') }}">index</a></li>
            <li><a href="{{ url_for('bots.get_dashboard') }}">Dashboard</a></li>
            <li><a href="{{ url_for('bots.get_index') }}">Bots index</a></li>
        </ul>
    </nav>
    {% endblock %}

    {% block main %}
    <main>
        <h1>Chessbots</h1>
        <p>some project.. o_O</p>
    </main>
    {% endblock %}
{% endblock %}

chessbots/board/templates/mockbots.html.j2
{% extends 'base.html.j2' %}
{% block title %}mockbots test result{% endblock title %}

{% macro position(bot, captcha) %}
    <pre class="position">
pos: {{ captcha.position }}
{% for check in captcha.position_checks if check.usable %}
{{ check.usable }} solved:{{ check.rs_position }} snpos:{{ check.snapshot_pos.txt }} r{{ check.rotation }} s{{ check.read_style }}
{{ check.note }}

{{ check.pattern.txt() }}

bit values:
{% for section in check.sections -%}
{{ section.bit_raw }} {{ section.bit_value }} {{ section.bit_check }} {{ section.check_expect }} {{ section.bit_int }} {{ section.grid_value().txt }}
{% endfor %}



{% endfor %}
        </div>
</pre>

{% endmacro %}

{% macro print_board(board, name) %}
    <div>
        <span>{{ name }}</span>
        <pre>{{ board|replace('2', '.')|replace('0', 'o') }}</pre>
    </div>
{% endmacro %}
{% macro image_link(bot, name) %}
    {% set img_path = bot.picture() ~ '_' ~ name ~ '.jpg' %}
    {% if '' == name %}
        {% set img_path = bot.picture() %}
        {% set name = 'raw' %}
    {% endif %}
    <a href="{{ img_path }}" target="_blank">
        <span>{{ name }}</span>
        <img src="{{ img_path }}"/>
    </a>
{% endmacro %}


{% block body %}
    <main>
        <nav id="dbg"></nav>
        <span>sum: {{ result|length }}</span>
        {% for bot, captcha, res, ang_res, target_pos in result %}
            <section class="result test-{{ 'pass' if res and ang_res else 'fail' }}">
        <span class="title">
            <span class="name">{{ bot.name }}:</span>
            <span class="test_result">{{ 'ok' if res else 'F' }}</span>
            <span class="test_result">{{ 'ok' if ang_res else 'F' }}</span>
            <span class="pos">cp:{{ captcha.position.txt }}</span>
            <span class="pos">tp:{{ target_pos.txt }}</span>
            <span class="pos">tp:{{ captcha.position_checks|length }}</span>
            <span class="angle">rot:{{ captcha.rotation }}</span>
            <span class="angle">ca:{{ captcha.angle }}</span>
            <span class="angle_points">ap:{{ captcha.angle_points[0].txt }} {{ captcha.angle_points[1].txt }} {{ captcha.angle_points[2].txt }}</span>
        </span>
                <div class="content">

                    <div class="txt_grids">
                        {{ print_board(bot.pattern.txt(), 'target') }}
                        {{ print_board(captcha.board.txt(), 'result') }}
                        {{ print_board(captcha.grid_txt, 'raw') }}
                    </div>

                    <div class="pictures">
                        {{ image_link(bot, 'angle') }}
                        {{ image_link(bot, 'markers') }}
                        {{ image_link(bot, 'pos') }}
                        {{ image_link(bot, 'value') }}
                        {{ image_link(bot, 'grid') }}
                        {{ image_link(bot, 'grid_expect') }}
                        {{ image_link(bot, '') }}
                    </div>
                    {{ position(bot, captcha) }}

                    <div class="markers" style="display: none">
                        {% for m in captcha.markers %}
                            <span class="pos">{{ m.pos }}</span>
                            <span class="value">{{ m.valid_size }}</span>
                            <span class="value">{{ m.radius }}</span>
                            <span class="value">{{ m.value }}</span>
                        {% endfor %}
                    </div>
                </div>
            </section>
        {% endfor %}
    </main>

{% endblock body %}

{% block head %}

    <script>

        document.addEventListener("DOMContentLoaded", function () {
            function createElement(type, options) {
                var element = document.createElement(type)
                if (options) {
                    if (options['attributes'] !== undefined) {
                        for (name in options.attributes) {
                            element.setAttribute(name, options.attributes[name])
                        }
                    }
                    if (options['classes'] !== undefined) {
                        for (c of options.classes) {
                            element.classList.add(c);
                        }
                    }
                    if (options['id'] !== undefined) {
                        element.id = options.id
                    }
                    if (options['txt'] !== undefined) {
                        element.appendChild(document.createTextNode(options.txt))
                    }
                    if (options['src'] !== undefined) {
                        element.src = options.src
                    }
                    if (options['dataset'] !== undefined) {
                        for (d in options.dataset) {
                            element.dataset[d] = options.dataset[d]
                        }
                    }
                    if (options['click'] !== undefined) {
                        element.addEventListener('click', options.click)
                    }
                    if (options['children'] !== undefined) {
                        for (child of options.children) {
                            element.appendChild(child)
                        }
                    }
                }

                return element
            }

            function traverse_results() {
                var elementList = document.querySelectorAll("section.result")
                elementList.forEach(function (node, idx) {
                    var show = node.classList.contains('test-pass') ? "none" : "block"
                    var result = node.querySelector(".content")

                    //result.style.display = show
                    result.style.display = 'none'
                });
            }

            function create_debug_bar() {
                all_on = createElement('span', {
                    txt: 'all_on',
                    click: function (event) {
                        event.preventDefault()

                        var elementList = document.querySelectorAll("section.result .content")
                        elementList.forEach(function (node, idx) {
                            node.style.display = 'block'
                        });
                    }
                });

                all_off = createElement('span', {
                    txt: 'all_off',
                    click: function (event) {
                        event.preventDefault()

                        var elementList = document.querySelectorAll("section.result .content")
                        elementList.forEach(function (node, idx) {
                            node.style.display = 'none'
                        });
                    }
                });

                on_off = createElement('span', {
                    txt: 'on/off',
                    click: function (event) {
                        event.preventDefault()
                        traverse_results()
                    }
                });

                dbg = document.getElementById('dbg')
                dbg.appendChild(all_on)
                dbg.appendChild(all_off)
                dbg.appendChild(on_off)


            }

            function add_click_title() {
                var elementList = document.querySelectorAll("section.result")
                elementList.forEach(function (node, idx) {
                    var title = node.querySelector(".title")
                    title.addEventListener('click', function (event) {
                        event.preventDefault()
                        var show = node.style.display == 'block' ? 'none' : 'block'
                        console.log('show', show, node.style.display, node.style)
                        var result = node.querySelector(".content")
                        result.style.display = show
                    })
                });

            }

            traverse_results()
            create_debug_bar()
            add_click_title()
        });

    </script>
    <style>
        section {
            display: block;
            font-family: monospace;
        }

        section.test-fail {
            background-color: #fcb1b1;
            margin-bottom: 1px;
        }

        section.test-pass {
            background-color: #a3ffbf;
        }

        #section.test-pass > .content {
            display: none;
        }

        section > .title {
            display: block;
        }

        section > .title > span {
            display: inline-block;
            width: 4em;
            height: 1em;
        }

        section > .title > span.name {
            width: 6em;
        }

        section > .title > span.test_result {
            width: 2em;
        }

        section > .title > span.pos {
            width: 4em;
        }

        section > .title > span.angle {
            width: 5em;
            overflow: hidden;
        }

        section > .title > span.angle_points {
            width: 17em;
        }

        .pictures {
            display: inline-flex;
            height: 12em;
        }

        .pictures a {
            width: 10em;
            height: 10em;
            display: inline-block
        }

        .pictures a span {
            display: inline-block;
        }

        .pictures a img {
            width: 10em;
            height: 10em;
            display: inline-block
        }

        .txt_grids > div {
            display: inline-block
        }

    </style>
{% endblock head %}